<?php

namespace MyApp\UserBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * BakeryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinistreAutomobileRepository extends EntityRepository
{
    public function findByidautomobile($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT a.address,a.latitude,a.longitude FROM  SinistreAutomobileBundle:SinistreAutomobile a WHERE a.idautomobile= :id")
            ->setParameter('id',$id);
        return $q->getResult();
    }
    public function findByNom($p){

        $query=$this->getEntityManager()->createQuery("SELECT m from SinistreAutomobileBundle:SinistreAutomobile m where m.localisation like :x")
            ->setParameter('x','%'.$p.'%');
        return $query->getResult();

    }



}
