<?php
/**
 * Created by PhpStorm.
 * User: sarra
 * Date: 2/22/2019
 * Time: 12:39 PM
 */

namespace Sarah\BackBundle\Repository;


/**
 * paquetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paquetRepository extends \Doctrine\ORM\EntityRepository
{

}
