<?php
/**
 * Created by PhpStorm.
 * User: sarra
 * Date: 2/22/2019
 * Time: 12:39 PM
 */

namespace Sarah\BackBundle\Repository;


/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends \Doctrine\ORM\EntityRepository
{
    public function finddd($x)
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a.type')
            ->where('a.id=:p')
            ->setParameter(':p',$x)
            ->getQuery()
            ->getResult();
    }
}
