<?php
/**
 * Created by PhpStorm.
 * User: sarra
 * Date: 2/22/2019
 * Time: 12:39 PM
 */

namespace Sarah\BackBundle\Repository;


/**
 * promotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class promotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindPromotionsExpirired()
    {
        return $this
            ->createQueryBuilder('a')
            ->select('a')
            ->where('a.DateFinPromotion <= :today')
            ->setParameter('today',new \DateTime())
            ->getQuery()
            ->getResult()
            ;
    }

}
